language: node_js
node_js:
- 12
addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"
env:
  global:
  before_script:
- npm run-script build
before_deploy:
- openssl aes-256-cbc -K $encrypted_081d3a392e1a_key -iv $encrypted_081d3a392e1a_iv
  -in deploy-key.pem.enc -out deploy-key.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key.pem
- ssh-add deploy-key.pem
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR
    $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master